name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this to the branch that you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Artifactory Docker Registry
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v1
        with:
          registry: idani.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t idani.jfrog.io/docker-local/davidfirstpipline:latest .

      # Setup JFrog CLI
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          # JFrog platform url
          JF_URL: 'https://idani.jfrog.io'
          # Basic authentication credentials
          JF_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Configure JFrog CLI
      - name: Configure JFrog CLI
        run: |
          # Assuming your JFrog CLI should be configured for Artifactory
          jf c add artifactori --url=https://idani.jfrog.io --user=${{ secrets.ARTIFACTORY_USERNAME }} --password=${{ secrets.ARTIFACTORY_PASSWORD }} --interactive=false

      # Scan the Docker image with JFrog CLI
      - name: Scan Docker Image Locally with JFrog CLI
        run: |
          jfrog docker scan idani.jfrog.io/docker-local/davidfirstpipline:latest

      # Push the Docker image to Artifactory
      - name: Push Docker Image
        run: |
          docker push idani.jfrog.io/docker-local/davidfirstpipline:latest