name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Docker Registry (Artifactory)
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://idani.jfrog.io/ui/login/
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t idani.jfrog.io/docker-local/davidfirstpipline:latest .

      # Push the Docker image to Artifactory
      - name: Push Docker Image
        run: |
          docker push idani.jfrog.io/docker-local/davidfirstpipline:latest
