name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this to the branch that you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Artifactory Docker Registry
      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v1
        with:
          registry: idani.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t idani.jfrog.io/docker-local/davidfirstpipline:latest .

      # Scan the Docker image with JFrog Xray using JFrog CLI
      - name: Scan Docker Image Locally with JFrog CLI
        env:
          JFROG_URL: 'https://idani.jfrog.io'
          JFROG_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          # Install the JFrog CLI
          curl -fL https://getcli.jfrog.io | sh && sudo mv jfrog /usr/local/bin/
          
          # Configure JFrog CLI
          jf c add artifactori --url=https://idani.jfrog.io --user=dudi --password=Passdudi12! --interactive=false

          # Scan the Docker image locally
          jfrog docker scan idani.jfrog.io/docker-local/davidfirstpipline:latest
          
      # Push the Docker image to Artifactory
      - name: Push Docker Image
        run: |
          docker push idani.jfrog.io/docker-local/davidfirstpipline:latest
